---
- name: Compliance Connection Test
  hosts: web
  gather_facts: no

  tasks:
  - name: Collect only kernel facts
    ansible.builtin.shell: |
      rpm -qa --last | grep kernel-`uname -r`| sed 's/\s*|/|/g'
    register: shell_output

    